name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual execution

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC Assume Role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::329599657799:role/GitHubActionsTerraformRole
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: cd Practice && terraform init

      - name: Terraform Destroy
        run: cd Practice && terraform destroy -auto-approve
